version = 0.1
[default.deploy.parameters]
stack_name = "data-enrichment-prod"
resolve_s3 = true
s3_prefix = "data-enrichment-prod"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "S3BucketName=\"{'Fn::Sub': '${AWS::StackName}-data-${AWS::AccountId}'}\""
image_repositories = []
